# Generated by Django 4.0.1 on 2022-01-12 21:12

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmLoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Farm Name')),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('prod_type', models.CharField(max_length=100, verbose_name='Production Type')),
                ('farm_type', models.CharField(max_length=100, verbose_name='Farm Type')),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('pnt', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alerts', models.BooleanField(default=False, verbose_name='Email Alerts')),
                ('low_dens', models.BooleanField(default=False, verbose_name='Low Density')),
                ('med_dens', models.BooleanField(default=False, verbose_name='Medium Density')),
                ('high_dens', models.BooleanField(default=False, verbose_name='High Density')),
                ('on_prop', models.BooleanField(default=False, verbose_name='On Property')),
                ('two_km', models.BooleanField(default=False, verbose_name='2 km Radius')),
                ('five_km', models.BooleanField(default=False, verbose_name='5 km Radius')),
                ('ten_km', models.BooleanField(default=False, verbose_name='10 km Radius')),
                ('daily', models.CharField(choices=[('Always', 'Always'), ('Detect', 'Only when waterfowl are detected')], max_length=50, verbose_name='Daily')),
                ('weekly', models.CharField(choices=[('Always', 'Always'), ('Detect', 'Only when waterfowl are detected')], max_length=50, verbose_name='Weekly')),
                ('emails', models.CharField(default='', max_length=250, verbose_name='Alert Emails (separate with comma)')),
                ('farm', models.ManyToManyField(to='tracker.FarmLoc')),
            ],
        ),
    ]
