# Generated by Django 4.0.1 on 2022-01-14 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_notification_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmloc',
            options={'verbose_name': 'Farm', 'verbose_name_plural': 'Farms'},
        ),
    ]
