# Generated by Django 4.0 on 2022-02-22 22:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_remove_notification_daily_remove_notification_weekly_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmBuffer',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('parent_id', models.BigIntegerField()),
                ('owner_id', models.BigIntegerField()),
                ('dist1', models.CharField(max_length=100, verbose_name='Distance')),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
            options={
                'db_table': 'farmsbuffer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FarmWaterfowlDensities',
            fields=[
                ('date1', models.DateField()),
                ('farm_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('owner_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=100, verbose_name='Farm Name')),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('density_onfarm', models.CharField(max_length=10, verbose_name='Waterfowl density on farm')),
                ('density_2km', models.CharField(max_length=10, verbose_name='Waterfowl density within 2km of farm')),
                ('density_5km', models.CharField(max_length=10, verbose_name='Waterfowl density within 5km of farm')),
                ('density_10km', models.CharField(max_length=10, verbose_name='Waterfowl density within 10km of farm')),
            ],
            options={
                'db_table': 'farmsmodel',
                'managed': False,
            },
        ),
    ]
