# Generated by Django 4.0.1 on 2022-02-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_farmbuffer_farmwaterfowldensities'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Notification Name'),
        ),
    ]
