# Generated by Django 3.2.5 on 2022-08-23 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_notification_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RasterLinks',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('filedate', models.CharField(max_length=100, verbose_name='Date')),
                ('linkname', models.CharField(max_length=100, verbose_name='Link')),
            ],
            options={
                'db_table': 'raster_links',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='farmloc',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
