# Generated by Django 4.0.1 on 2022-08-23 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_auto_20220823_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmloc',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
